#!/bin/bash

if [ ! -d "/hda" ]; then
  echo "File system no present";
  exit;
fi

python /hda/pre-compile.py $@

# python compile-helper.py $@
arm-linux-gnueabi-gcc \
-fprofile-arcs \
-ftest-coverage \
-Wall \
$@ \
-lpthread

python /hda/post-compile.py $@
